// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9y-ecuW0eou2YrvPUbKl9eeOTGI8Iqk',
    appId: '1:874571358960:web:e125de218b36a63556d835',
    messagingSenderId: '874571358960',
    projectId: 'spotify-df933',
    authDomain: 'spotify-df933.firebaseapp.com',
    storageBucket: 'spotify-df933.firebasestorage.app',
    measurementId: 'G-Z1EJQS04SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfovEH-tkfZ-jZ2KsISle7l8glhBZoVXQ',
    appId: '1:874571358960:android:505105b026ba897256d835',
    messagingSenderId: '874571358960',
    projectId: 'spotify-df933',
    storageBucket: 'spotify-df933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2ehcNyMpB7TuWQpgl3eUDc-E5cBF50A',
    appId: '1:874571358960:ios:37b580c578f446cf56d835',
    messagingSenderId: '874571358960',
    projectId: 'spotify-df933',
    storageBucket: 'spotify-df933.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2ehcNyMpB7TuWQpgl3eUDc-E5cBF50A',
    appId: '1:874571358960:ios:37b580c578f446cf56d835',
    messagingSenderId: '874571358960',
    projectId: 'spotify-df933',
    storageBucket: 'spotify-df933.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9y-ecuW0eou2YrvPUbKl9eeOTGI8Iqk',
    appId: '1:874571358960:web:e9f841f7bb42275456d835',
    messagingSenderId: '874571358960',
    projectId: 'spotify-df933',
    authDomain: 'spotify-df933.firebaseapp.com',
    storageBucket: 'spotify-df933.firebasestorage.app',
    measurementId: 'G-QJ4ED93T1K',
  );
}
